### ISSUE TITLE
Type of Charts

### ISSUE THREAD

**Issue by ghost** [WillRod42/meteor#3]
We will probably need 3 different types of charts to answer all three of the distinct questions outlined in the project proposal text file. We should decide on what kinds of charts would be best to visualize the different types of data.

**Comment by billy0wang** [comment]
1. How often/when do meteorites strike the earth?
-- For this question, I think it would actually be cool if we use a scatterplot and graph it with
y-axis being the 12 months, and the x-axis being 31 days, so each point on the graph would be a date
of when a meteorite landed, and then we can see which receive more meteorites and also if there's a tendency for meteorites to land at a certain time of the month. 
2. Where on the earth are meteorites landing?
---- For this, I think we can use an interactive map, like we did for the shootings assignment.  Except, 
it would probably have to be a global map, with the ability to zoom into continents/countries/etc. Gonna be harder to implement than the shootings assignment.
3. What type of meteorites are striking the earth?
--- We could put this detail with the interactive map, like when you hover over, you show the specifications of that meteorite/event. I think this would make more sense if there are a ton of different 
meteorites. But if the same lets say 5 -10 types of meteorites are consistently dropping, then we could do like a pie chart or even a bar graph
